name: healthcelerate
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #Commons
  nb_utils: ^7.1.8
  google_fonts: ^6.1.0
  html: ^0.15.4
  http: ^1.2.1
  intl: 
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.11
  flutter_vector_icons: ^2.0.0
  lottie: ^3.3.2
  flutter_svg: ^2.0.8
  flutter_svg_provider: ^1.0.6
  stream_transform: ^2.1.0
  flutter_local_notifications: ^19.5.0
  carousel_slider: ^5.1.1
  flutter_spinkit: ^5.2.0
  responsive_navigation_bar: ^6.2.0
  date_picker_timeline: ^1.2.5

  #firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  firebase_crashlytics: ^5.0.5
  firebase_messaging: ^16.0.4

  # SOCIAL LOGIN
  the_apple_sign_in: ^1.1.1
  google_sign_in: ^7.2.0
  googleapis: ^15.0.0
  googleapis_auth: ^2.0.0
  extension_google_sign_in_as_googleapis_auth: ^3.0.0
  permission_handler: ^12.0.1

  # State Management
  get: ^4.6.5

  #Storage
  get_storage: ^2.1.1

  #PhotoViewGallery
  photo_view: ^0.15.0

  #Pickers
  file_picker: ^10.3.7
  image_picker: ^1.0.4
  country_picker: ^2.0.21

  # Google Map
  # google_maps_flutter: ^2.5.0
  # geolocator: ^10.1.0
  # geocoding: ^2.1.1

  # Payment
  # flutter_stripe: 10.1.1
  razorpay_flutter: ^1.3.6

  # new package from other 2nd app
  convex_bottom_bar: ^3.1.0+1
  flutter_iconly: ^1.0.2
  font_awesome_flutter: ^10.2.1
  timeline_tile: ^2.0.0
  flutter_feather_icons: ^2.0.0+1
  webview_flutter: ^4.4.2
  videosdk: ^3.2.0
  awesome_notifications: ^0.10.1


  flutter_localizations:
    sdk: flutter
  percent_indicator: ^4.2.3
  provider: ^6.1.2
  # get_it: ^7.6.0
  flutter_secure_storage: ^10.0.0
  path_provider: ^2.1.4
  time_picker_spinner_pop_up: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"
  remove_alpha_ios: true


dependency_overrides:
  archive: ^3.6.1
  win32: ^5.5.3

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/flags/
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/icons/navigation/
    - assets/icons/social_media/
    - assets/images/walkthrough_images/
