name: kivicare_patient
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #Commons
  nb_utils: ^6.1.0
  google_fonts: ^6.1.0
  html: ^0.15.4
  http: ^1.2.1
  intl: 
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.11
  flutter_vector_icons: ^2.0.0
  lottie: ^2.5.0
  flutter_svg: ^2.0.8
  flutter_svg_provider: ^1.0.6
  stream_transform: ^2.1.0
  flutter_local_notifications: ^17.1.2
  slider_button: ^2.0.0
  carousel_slider: ^4.2.1
  flutter_spinkit: ^5.2.0
  responsive_navigation_bar: ^3.2.8+1
  date_picker_timeline: ^1.2.5

  #firebase
  firebase_core: ^2.31.1
  firebase_auth: ^4.19.6
  firebase_crashlytics: ^3.5.6
  firebase_messaging: ^14.9.2

  # SOCIAL LOGIN
  the_apple_sign_in: ^1.1.1
  google_sign_in: ^6.2.1
  googleapis: ^11.4.0
  googleapis_auth: ^1.4.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.9
  permission_handler: ^11.0.1

  # State Management
  get: ^4.6.5

  #Storage
  get_storage: ^2.1.1

  #PhotoViewGallery
  photo_view: ^0.14.0

  #Pickers
  file_picker: ^5.5.0
  image_picker: ^1.0.4
  country_picker: ^2.0.21

  # Google Map
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1

  # Payment
  # flutter_stripe: 10.1.1
  razorpay_flutter: ^1.3.6

  # new package from other 2nd app
  convex_bottom_bar: ^3.1.0+1
  flutter_iconly: ^1.0.2
  font_awesome_flutter: ^10.2.1
  timeline_tile: ^2.0.0
  flutter_feather_icons: ^2.0.0+1
  webview_flutter: ^4.4.2
  videosdk: ^1.1.3


  flutter_localizations:
    sdk: flutter
  percent_indicator: ^4.2.3
  provider: ^6.1.2
  # get_it: ^7.6.0
  flutter_secure_storage: ^8.0.0
  path_provider: ^2.1.4
  time_picker_spinner_pop_up: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/flags/
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/icons/navigation/
    - assets/icons/social_media/
    - assets/images/walkthrough_images/
